// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKdNYRj6hl76-PClOa7iRml1VRefX2GOY',
    appId: '1:643655047949:web:330a3e610318a3c6612e44',
    messagingSenderId: '643655047949',
    projectId: 'mapshospital-f5561',
    authDomain: 'mapshospital-f5561.firebaseapp.com',
    storageBucket: 'mapshospital-f5561.appspot.com',
    measurementId: 'G-0EZGG3T8QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSx9cFpzSP6O9I27Qqj_abdrWN6ZaWa6o',
    appId: '1:643655047949:android:0494eb8c2b231b97612e44',
    messagingSenderId: '643655047949',
    projectId: 'mapshospital-f5561',
    storageBucket: 'mapshospital-f5561.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD86JrFvbBOq8jddBMUupcqi2GY8GXMa2Y',
    appId: '1:643655047949:ios:e2f31942135d6559612e44',
    messagingSenderId: '643655047949',
    projectId: 'mapshospital-f5561',
    storageBucket: 'mapshospital-f5561.appspot.com',
    iosClientId: '643655047949-dpeh6via0un8eau9hakb9vg3t8rp0c8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.hospitalMaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD86JrFvbBOq8jddBMUupcqi2GY8GXMa2Y',
    appId: '1:643655047949:ios:e2f31942135d6559612e44',
    messagingSenderId: '643655047949',
    projectId: 'mapshospital-f5561',
    storageBucket: 'mapshospital-f5561.appspot.com',
    iosClientId: '643655047949-dpeh6via0un8eau9hakb9vg3t8rp0c8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.hospitalMaps',
  );
}
